# Generated by Django 4.2.7 on 2023-12-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_answer_rating_alter_question_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(null=True),
        ),
    ]
