# Generated by Django 4.2.7 on 2023-12-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='profile',
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.OneToOneField(default=13, on_delete=django.db.models.deletion.CASCADE, to='app.rating'),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to='app.rating'),
        ),
        migrations.AddField(
            model_name='rating',
            name='profile',
            field=models.ManyToManyField(to='app.profile'),
        ),
    ]
