# Generated by Django 4.2.7 on 2023-12-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_answer_rating_remove_question_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.rating'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.rating'),
        ),
    ]
